name: Testes Automatizados

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  pytest:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout do código
        uses: actions/checkout@v3

      - name: 🐍 Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: 📦 Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: 🧪 Executar testes
        run: |
          pytest test_utils.py --disable-warnings -v

      - name: 📣 Notificar Microsoft Teams
        if: always()
        run: |
          status="${{ job.status }}"
          curl -H 'Content-Type: application/json' \
            -d "{\"@type\": \"MessageCard\", \"@context\": \"http://schema.org/extensions\", \"summary\": \"Status dos testes\", \"themeColor\": \"0076D7\", \"title\": \"CI GitHub - Testes Automatizados\", \"text\": \"Resultado: **${status}**\"}" \
            https://INSIRA_SUA_WEBHOOK_AQUI
